steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/meshpluspoi', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/meshpluspoi']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: bash
  args:
  - '-c'
  - |
    gcloud run deploy poi --image=gcr.io/$PROJECT_ID/meshpluspoi --region=asia-east1 --platform=managed --allow-unauthenticated
    gcloud run services update-traffic poi --region=asia-east1 --to-latest
# images:
# - gcr.io/$PROJECT_ID/meshpluspoi'